micronaut:
  application:
    name: micronautSecurity
  security:
    enabled: true
    intercept-url-map:
      -
        pattern: /admin/*
        http-method: GET
        access:
          - ROLE_ADMIN 
      -
        pattern: /super/admin/*
        http-method: GET
        access:
          - ROLE_SUPER 
      -
        pattern: /welcome
        http-method: GET
        access:
          - isAnonymous()
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
jpa:
 default:
    entity-scan:
      packages: 'micronaut.security.model'
    properties:
      hibernate:
         hbm2ddl:
          auto: update
         show_sql: true 
datasources:
     default:
      url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/micronaut`}
      username: ${JDBC_USER:postgres}
      password: ${JDBC_PASSWORD:123@admin}
      driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}        